name: 'Execute-Terraform-On-GCP-Main-Branch'

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'GCP subfolder to deploy (e.g., _gcpBuckets or _gcpServiceAccounts)'
        required: true
        default: '_gcpBuckets'


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Show input folder
      run: echo "Folder selected:" ${{ github.event.inputs.folder }}
          
    - name: Show current directory
      run: pwd && ls -la

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Show contents of folder
      run: |
          pwd
          ls -la gcp/${{ github.event.inputs.folder }}


    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: gcp/${{ github.event.inputs.folder }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: gcp/${{ github.event.inputs.folder }}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: gcp/${{ github.event.inputs.folder }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: gcp/${{ github.event.inputs.folder }}
