name: 'Execute-Terraform-On-GCP-Main-Branch'

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'GCP subfolder to deploy (e.g., _gcpBuckets or _gcpServiceAccounts)'
        required: true
        default: '_gcpBuckets'


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: gcp/${{ github.event.inputs.folder }}

    steps:
    - name: Show input folder
      run: echo "Folder selected:" ${{ github.event.inputs.folder }}

    - name: Debug working directory
        run: |
          echo "Folder selected: ${{ github.event.inputs.folder }}"
          pwd
          ls -la
          
    - name: Show current directory
      run: pwd && ls -la

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout repo
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
